version: "3"
services:

  nginx:
    image: nginx:latest
    volumes:
      - ./public:/public
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks: 
      codeigniter_net:
    ports:
      - "8181:90"
    restart: always

  php:
    build: 
      context: ./public
      dockerfile: Dockerfile
    volumes:
      - ./public:/public
    depends_on:
      - mariadb
    networks:
      codeigniter_net:

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER:  renato 
      MYSQL_PASSWORD: password
    networks:
      codeigniter_net:
    expose:
      - "3306"
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mariadb-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    expose:
      - "8082"
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_USERNAME:root
      - MYSQL_ROOT_PASSWORD:password
    depends_on:
      - mariadb
    networks:
      codeigniter_net:

networks:
  codeigniter_net:
volumes:
  mariadb-data:
